### ISSUE TITLE
Why don't you use pip or torch.hub ?

### ISSUE THREAD

**Issue by kadirnar** [RizwanMunawar/yolov5-object-tracking#1]
Hello @RizwanMunawar,

Why don't you use pip or torch.hub so the Yolov5 codes are more up to date?

Yolov5-Pip:  https://github.com/fcakyon/yolov5-pip
Yolov5 Hub: https://docs.ultralytics.com/tutorials/pytorch-hub/

Example : https://github.com/goksenin-uav/tracker-hub

**Comment by RizwanMunawar** [comment]
@kadirnar! We can use both, but due to more custom functionality, I preferred Pip. Pytorch hub code does not provide more custom implementation functionality. i.e If you want to blur the detected objects, how you will do that in Pytorch hub code?

**Comment by kadirnar** [comment]
You don't need to upload data, models and utils files. You just have to ```pip install yolov5.```

Example Inference Code:

```
import yolov5

# load pretrained model
model = yolov5.load('yolov5s.pt')

# set model parameters
model.conf = 0.25  # NMS confidence threshold
model.iou = 0.45  # NMS IoU threshold

# set image
img = 'https://github.com/ultralytics/yolov5/raw/master/data/images/zidane.jpg'

# inference with larger input size
results = model(img, size=1280)

# parse results
predictions = results.pred[0]
boxes = predictions[:, :4] # x1, y1, x2, y2
scores = predictions[:, 4]
categories = predictions[:, 5]
```
My Work:
https://github.com/goksenin-uav/dethub/blob/main/dethub/model.py#L36-L70

**Comment by RizwanMunawar** [comment]
Sure, I will look into that. Thanks @kadirnar
