### ISSUE TITLE
Streamlit from webcam

### ISSUE THREAD

**Issue by t3ch9** [RizwanMunawar/yolov5-object-tracking#2]
Hello, how can I perform object detection from webcam (source 0) with Streamlit?

**Comment by RizwanMunawar** [comment]
@t3ch9! You can perform object detection on webcam using mentioned command below.
`python ob_detect.py --weights yolov5s.pt --source 0 --view-img`

If you want to use webcam in streamlit dashboard, you will see the option for selection for webcam on dashboard. Select that option and you will able to use webcam.

**Comment by t3ch9** [comment]
I am interested to perform object detection on webcam didn't see any option in Streamlit for webcam. Am I doing something wrong by running: python -m streamlit run app.py
![image](https://user-images.githubusercontent.com/29530317/199063104-074447de-bacc-4d59-a401-38a666613854.png)

**Comment by RizwanMunawar** [comment]
@t3ch9  In Streamlit dashboard, I have not added option of webcam. I will add the feature asap.

**Comment by RizwanMunawar** [comment]
@t3ch9 I added the webcam module in streamlit dashboard. You can clone the latest code and can use webcam feature in dashboard.
